---
title: "A walkthrough of the expected patterns for the threshold approach."
output: 
    html_document:
        fig_width: 7
        fig_height: 6
        fig_caption: true
---

For an understanding of the observed slope pattern with positive biodiversity effects at low threshold levels and negative diversity effects at high threshold levels, it helps to consider only the endpoints of the relationship, i.e. the monocultures and the full species-mixture (Fig. 5). Fig. 5 shows a scenario with 12 species performing 10 functions where the function values have been drawn from a uniform distribution (0, 1) and standardised between 0 and 1. The function values for each species as well as the average function value across species is shown in **a**. **b** shows the slope of the diversity-number of functions ≥ threshold relation- ship between the monocultures and the full mixture, excluding intermediate diversity levels. **c** shows the corresponding slopes plotted against the threshold levels. Fig. 5 b makes it clear that the number of functions that the monocultures sustained above a given threshold continuously decreases with threshold level. It also shows that the full species mixture can only take discrete values for number of function ≥ threshold. The mixture will perform all functions above the threshold until the threshold value is higher than the lowest average function value (here 38%). If that threshold value is crossed, the number of functions ≥ threshold will drop, from 10 to 9 functions in our example, until the threshold value is higher then the next highest average function value at which point it will drop further. If the threshold is higher than the highest average function value (here 64%) the number of functions ≥ threshold that the mixture can sustain drops to 0. Hence, in the threshold interval between the lowest average function value (38%) and the highest average function value (64%) the number of functions ≥ threshold that the full mixture can sustain drops from all ten to none. This corresponds to the interval between the highest positive slope and the highest negative slope. Note that the slopes shown here do not correspond exactly to the slopes that one gets if all intermediate diversity levels are taken into account. The point however, is the same: the driver of the slopes of the *diversity ∼ multifunctionality* relationship in the multithreshold approach is the number of functions the full mixture can sustain above the threshold level, which is determined by the distribution of the function values. The change in sign of the slopes occurs after the threshold corresponding to the median of the mean function values. Or put more simply, when the threshold level is higher than more than half of the mean function values. In the extreme case where all functions have the same mean value, the number of functions sustained by the full mixture can only take two values: all or none. The slope will drop from maximum positive to maximum negative as soon as the threshold value is higher than the mean function value. While this might be an unlikely scenario, it still emphasises the fact that a sensible ecological interpretation of the slope pattern is challenging.


![**Figure 5. A mechanistic explanation of the multi threshold approach.** **a**, The standardised function values for 12 species (A-L) and 10 functions (F 1 - F 10), and the average value for a mixture of all 12 species. **b**, The slopes for the number of functions performed above a threshold for all thresholds between 5% and 95% with a step-size of 0.1%. The colours mark which bundle of slopes include the same value for the mixture. The colours alternate to differentiate adjacent bundles but have no other meaning. **c**, The slopes plotted against the threshold levels. The colours correspond to **b**. The numbers next to the slopes show the threshold levels at which the number of functions above the threshold change for the full mixture - which corresponds to the average function values shown in **a**. The dotted lines show the actual datapoint referred to by the plotted numbers.](Figure_5.png)

